"""
utils/fallbacks.py
30 hand-crafted offline devotionals — rotated deterministically by day-of-year.
Used when Gemini quota is exhausted so the app always feels intentional.
All entries use canonical schema: reference, text, topic,
explanation, reflection, application, memory, prayer.
"""
from datetime import date

OFFLINE_DEVOTIONALS = [
    {
        "reference": "Psalm 46:10",
        "text": "Be still, and know that I am God.",
        "topic": "Peace",
        "explanation": "In one of the most active Psalms, God interrupts the noise with a single command — stop. The word 'still' means to let go, to release the grip. Knowing God here is not an intellectual exercise but an act of surrender.",
        "reflection": "What are you gripping today that this verse is asking you to release?",
        "application": "Spend two minutes in complete silence before your first conversation today.",
        "memory": "Stillness before God is not emptiness — it is arrival.",
        "prayer": "Lord, I am full of noise today. Teach me what it means to stop long enough to know You are here. Amen.",
    },
    {
        "reference": "Isaiah 40:31",
        "text": "But they that wait upon the Lord shall renew their strength; they shall mount up with wings as eagles; they shall run, and not be weary; and they shall walk, and not faint.",
        "topic": "Strength",
        "explanation": "The Hebrew word for 'wait' carries the idea of twisting together — like a rope gaining strength through tension. Waiting on God is not passive resignation but active trust that weaves our weakness into something stronger.",
        "reflection": "Where in your life is waiting feel like losing — and what would it look like to see it as strengthening instead?",
        "application": "Name one thing you've been trying to force forward. Tell God you're releasing the timeline today.",
        "memory": "Waiting on God is where weakness becomes a rope.",
        "prayer": "Lord, I am tired of running on empty. Teach me to wait in a way that actually refills me. Amen.",
    },
    {
        "reference": "Romans 8:28",
        "text": "And we know that all things work together for good to them that love God, to them who are the called according to his purpose.",
        "topic": "Purpose",
        "explanation": "Paul doesn't say all things are good — he says they work together for good. The difference matters. A single ingredient in a recipe isn't the meal; context and time transform it. God is working with everything, not just the easy parts.",
        "reflection": "Is there something from your past you've never let be part of 'all things'? What would it mean to include it?",
        "application": "Write down one difficult thing from this season. Underneath it write: 'This is also being worked.'",
        "memory": "Not all things are good. All things are being worked.",
        "prayer": "God, I don't understand what You're doing with the hard parts. But I'm choosing today to believe they're in Your hands too. Amen.",
    },
    {
        "reference": "Proverbs 3:5-6",
        "text": "Trust in the Lord with all thine heart; and lean not unto thine own understanding. In all thy ways acknowledge him, and he shall direct thy paths.",
        "topic": "Wisdom",
        "explanation": "Leaning on your own understanding feels like wisdom because it uses real information. But our information is always partial. The instruction here is not to stop thinking — it's to hold your conclusions loosely enough that God can redirect them.",
        "reflection": "Where are you making a decision based only on what you can currently see?",
        "application": "Before one decision today, pause and say: 'I'm choosing this — and I'm open to being redirected.'",
        "memory": "Your understanding is real. It is also incomplete.",
        "prayer": "Lord, I keep trying to figure everything out before I trust You. Help me trust You before I figure everything out. Amen.",
    },
    {
        "reference": "Philippians 4:6-7",
        "text": "Be careful for nothing; but in every thing by prayer and supplication with thanksgiving let your requests be made known unto God. And the peace of God, which passeth all understanding, shall keep your hearts and minds through Christ Jesus.",
        "topic": "Anxiety",
        "explanation": "The word 'careful' here means full of care in a consuming way — the kind of worry that takes over. The remedy isn't to stop caring, but to redirect the energy of caring into specific, thankful prayer. What you bring to God, He guards in return.",
        "reflection": "What are you currently carrying as anxiety that could instead become a specific prayer?",
        "application": "Name your worry out loud to God — not as a complaint but as a request. Then name one thing you're thankful for in the same breath.",
        "memory": "Anxiety names what's wrong. Prayer names what's true.",
        "prayer": "Lord, I'm anxious today. I'm naming it rather than hiding it. I'm bringing it to You rather than carrying it alone. Amen.",
    },
    {
        "reference": "Jeremiah 29:11",
        "text": "For I know the thoughts that I think toward you, saith the Lord, thoughts of peace, and not of evil, to give you an expected end.",
        "topic": "Hope",
        "explanation": "This verse was written to people in exile — people who had every reason to believe God had forgotten them. The 'expected end' is not a guarantee of comfort but a guarantee of direction. Even in displacement, purpose was still being worked.",
        "reflection": "In what area of your life does it feel like God's good plan has been delayed or lost?",
        "application": "Find one small thing today that could be a sign of forward movement, even if tiny.",
        "memory": "God's thoughts toward you are plans, not afterthoughts.",
        "prayer": "Lord, I struggle to believe this verse applies to my current situation. Help my unbelief. Amen.",
    },
    {
        "reference": "Matthew 11:28",
        "text": "Come unto me, all ye that labour and are heavy laden, and I will give you rest.",
        "topic": "Strength",
        "explanation": "The invitation is not 'come when you have it together' but 'come specifically because you don't.' The word 'rest' here is not sleep — it's the rest of finding the right load after carrying the wrong one.",
        "reflection": "What burden are you carrying that was never meant to be yours to carry alone?",
        "application": "Put one thing down today — even mentally. Tell someone you trust that you're overwhelmed.",
        "memory": "The invitation is for the tired — not the ready.",
        "prayer": "Jesus, I'm tired in a way that sleep doesn't fix. I'm coming to You with that. Amen.",
    },
    {
        "reference": "1 Peter 5:7",
        "text": "Casting all your care upon him; for he cares for you.",
        "topic": "Anxiety",
        "explanation": "The word 'casting' is the same used for throwing a net — a decisive, deliberate release. The reason given is not that worry is weak, but that God's care is active. You are not giving God your problems; you are entering a relationship where your problems are shared.",
        "reflection": "What would actually change about today if you believed God was actively caring about your specific situation?",
        "application": "Tell one person today about something you've been carrying quietly.",
        "memory": "God's care for you is the reason, not the reward.",
        "prayer": "Lord, I give You the things I keep taking back. Help me actually let go this time. Amen.",
    },
    {
        "reference": "John 14:27",
        "text": "Peace I leave with you, my peace I give unto you: not as the world giveth, give I unto you. Let not your heart be troubled, neither let it be afraid.",
        "topic": "Peace",
        "explanation": "Jesus distinguishes His peace from the world's version. The world's peace is the absence of conflict. His peace is a settled centre that exists even inside conflict. It's not a feeling to achieve but a gift already given — the question is whether we receive it.",
        "reflection": "When you think of peace, do you think of it as something to earn or something already given?",
        "application": "Before reacting to something stressful today, take one breath and remember: the peace is already yours.",
        "memory": "His peace is not a reward for calm — it is a gift for the troubled.",
        "prayer": "Jesus, I want the peace You promised, not just the absence of noise. Teach me to receive it. Amen.",
    },
    {
        "reference": "Hebrews 11:1",
        "text": "Now faith is the substance of things hoped for, the evidence of things not seen.",
        "topic": "Faith",
        "explanation": "Faith is defined here not as feeling certain but as giving substance to hope — making the unseen real enough to act on. Evidence here is a legal term: faith is the proof offered before the verdict is in. It is not the absence of doubt but the decision to move anyway.",
        "reflection": "What decision have you been waiting to make until you felt more certain?",
        "application": "Take one small step today toward something you've been hoping for but haven't acted on.",
        "memory": "Faith makes hope solid before the outcome arrives.",
        "prayer": "Lord, I want to believe more than I feel like believing today. That's where I'm starting. Amen.",
    },
    {
        "reference": "Joshua 1:9",
        "text": "Have not I commanded thee? Be strong and of a good courage; be not afraid, neither be thou dismayed: for the Lord thy God is with thee whithersoever thou goest.",
        "topic": "Courage",
        "explanation": "The command to be courageous is given not because the danger isn't real, but because the presence is certain. Joshua was facing an actual military campaign. The strength here isn't self-confidence; it's confidence rooted in accompaniment.",
        "reflection": "What feels too big for you right now — and what would it mean to face it knowing you're not facing it alone?",
        "application": "Do the thing you've been avoiding today. Start with the smallest piece of it.",
        "memory": "Courage is not the absence of fear — it is fear with company.",
        "prayer": "Lord, I'm afraid of what's ahead. I'm asking You to walk into it with me. Amen.",
    },
    {
        "reference": "Ephesians 2:10",
        "text": "For we are his workmanship, created in Christ Jesus unto good works, which God hath before ordained that we should walk in them.",
        "topic": "Purpose",
        "explanation": "The Greek word for 'workmanship' is poiema — the root of our word 'poem.' You are not a problem God solved; you are a work God is composing. The works were prepared before you arrived — you are walking into a story already written with you in mind.",
        "reflection": "What 'good works' have been on your heart for a long time that you keep dismissing as too small or too unlikely?",
        "application": "Do one thing today that feels like the person God made you to be — even if no one notices.",
        "memory": "You are a poem God is still writing.",
        "prayer": "Lord, I want to live like I believe I was made on purpose. Help me walk into that today. Amen.",
    },
    {
        "reference": "Lamentations 3:22-23",
        "text": "It is of the Lord's mercies that we are not consumed, because his compassions fail not. They are new every morning: great is thy faithfulness.",
        "topic": "Hope",
        "explanation": "These words were written inside the ruins of Jerusalem. The author chose to remember faithfulness while surrounded by evidence of destruction. New mercy is not an automatic feeling — it is a deliberate turning toward what is true before the day gets going.",
        "reflection": "What would it mean to encounter God's mercy as genuinely new today — not yesterday's leftover?",
        "application": "Begin today before looking at your phone. Even sixty seconds of quiet acknowledgement counts.",
        "memory": "Mercy arrives before you open your eyes.",
        "prayer": "Lord, I'm receiving today's mercy as new. Not because I feel it yet, but because You said it. Amen.",
    },
    {
        "reference": "2 Corinthians 12:9",
        "text": "And he said unto me, My grace is sufficient for thee: for my strength is made perfect in weakness. Most gladly therefore will I rather glory in my infirmities, that the power of Christ may rest upon me.",
        "topic": "Strength",
        "explanation": "Paul asked three times for his suffering to be removed. The answer was not removal but sufficiency. The word 'sufficient' means 'it is enough for you right now.' This is not comfort from a distance — it is presence in the difficulty.",
        "reflection": "Is there a weakness you've been trying to hide from God, as if He doesn't already see it?",
        "application": "Tell someone one honest thing about where you're struggling today.",
        "memory": "Weakness is where His strength finds room.",
        "prayer": "Lord, I don't want to be weak. But I'm learning that weak is where You work. Amen.",
    },
    {
        "reference": "Psalm 23:1",
        "text": "The Lord is my shepherd; I shall not want.",
        "topic": "Faith",
        "explanation": "The claim 'I shall not want' is not a declaration of having everything — it is a declaration of being tended. A sheep in the care of a good shepherd lacks nothing it actually needs. The question this verse asks is whether we believe our Shepherd knows what we need.",
        "reflection": "What do you 'want' right now that you're not sure God cares about?",
        "application": "Bring one specific, honest want before God today — not as a demand, but as a conversation.",
        "memory": "The Lord shepherds — which means He tends what you lack.",
        "prayer": "Lord, I want things You haven't given me yet. I'm choosing to trust that You know what I need. Amen.",
    },
    {
        "reference": "Nehemiah 8:10",
        "text": "Then he said unto them, Go your way, eat the fat, and drink the sweet, and send portions unto them for whom nothing is prepared: for this day is holy unto our Lord: neither be ye sorry; for the joy of the Lord is your strength.",
        "topic": "Gratitude",
        "explanation": "The people were weeping when they heard the Word — convicted by how far they had drifted. Nehemiah's response was surprising: stop mourning, celebrate, and share with those who have nothing. Joy is not a reward for getting it right; it is the response to being found.",
        "reflection": "Where have you been treating mourning as more spiritual than celebration?",
        "application": "Do something generous today — give something away, share a meal, or pay for someone.",
        "memory": "The joy of the Lord strengthens — not rewards.",
        "prayer": "Lord, I forget that joy is part of how You sustain me. Restore it today. Amen.",
    },
    {
        "reference": "1 Corinthians 13:4-7",
        "text": "Charity suffereth long, and is kind; charity envieth not; charity vaunteth not itself, is not puffed up, doth not behave itself unseemly, seeketh not her own, is not easily provoked, thinketh no evil.",
        "topic": "Love",
        "explanation": "Every description of love here is a verb — something love does or refuses to do. It's a pattern of behaviour before it's a feeling. The hardest phrase is probably 'seeketh not her own' — love that doesn't keep score, doesn't calculate return.",
        "reflection": "Which of these descriptions is hardest for you to live out right now — and with whom?",
        "application": "Choose one person today and do something for them without expecting anything back.",
        "memory": "Love is a pattern of behaviour before it becomes a feeling.",
        "prayer": "Lord, I want love to be more than what I feel. Teach me to love the way this verse describes. Amen.",
    },
    {
        "reference": "Colossians 3:17",
        "text": "And whatsoever ye do in word or deed, do all in the name of the Lord Jesus, giving thanks to God and the Father by him.",
        "topic": "Gratitude",
        "explanation": "Doing 'in the name of' means doing as a representative — carrying the character of the one you represent. Everything becomes a means of reflecting something. The accompanying instruction is thanks — gratitude shifts ordinary actions into consecrated ones.",
        "reflection": "What task today feels the most disconnected from any spiritual meaning?",
        "application": "Do that task as if it matters — because it does. Name it as an offering before you start.",
        "memory": "Ordinary work done with thanks becomes sacred.",
        "prayer": "Lord, help me see today's ordinary moments as part of something larger. Amen.",
    },
    {
        "reference": "Psalm 103:2-3",
        "text": "Bless the Lord, O my soul, and forget not all his benefits: who forgiveth all thine iniquities; who healeth all thy diseases.",
        "topic": "Healing",
        "explanation": "The instruction 'forget not' implies that forgetting is exactly what we tend to do. Gratitude here is not a spontaneous feeling; it's an act of memory — deliberately recalling what has already been done. The soul has to be addressed, even commanded, to bless.",
        "reflection": "What has God done for you that you've stopped being grateful for because it became normal?",
        "application": "Write down three specific things God has done in the last year. Keep the list somewhere visible.",
        "memory": "Gratitude is memory on purpose.",
        "prayer": "Lord, I've forgotten more of Your goodness than I've remembered. Help me recall. Amen.",
    },
    {
        "reference": "Isaiah 43:1",
        "text": "But now thus saith the Lord that created thee, O Jacob, and he that formed thee, O Israel, Fear not: for I have redeemed thee, I have called thee by thy name; thou art mine.",
        "topic": "Purpose",
        "explanation": "The verse begins with 'But now' — after difficulty, after failure, after exile. The claim 'thou art mine' is not sentimental; it is legal. Redemption means a price was paid. Being called by name means you are known specifically, not generically.",
        "reflection": "Do you live as someone who is claimed and known — or as someone still trying to earn a place?",
        "application": "Say your own name out loud and add: 'God knows this name.' Then go about your day.",
        "memory": "You are claimed before you are capable.",
        "prayer": "Lord, I forget that I belong to You — not because I've earned it but because You said it. Amen.",
    },
    {
        "reference": "James 1:5",
        "text": "If any of you lack wisdom, let him ask of God, that giveth to all men liberally, and upbraideth not; and it shall be given him.",
        "topic": "Wisdom",
        "explanation": "The phrase 'upbraideth not' means God will not scold you for needing to ask. There is no implication that you should already know, or that asking is a sign of failure. Wisdom is available generously to anyone who recognises they're missing it.",
        "reflection": "What decision are you making right now without having asked God about it?",
        "application": "Actually ask God for wisdom about one specific thing today — not as a ritual but as a genuine request.",
        "memory": "God gives wisdom without making you feel foolish for needing it.",
        "prayer": "Lord, I need wisdom I don't have. I'm asking — and I'm trusting You to answer. Amen.",
    },
    {
        "reference": "Deuteronomy 31:6",
        "text": "Be strong and of a good courage, fear not, nor be afraid of them: for the Lord thy God, he it is that doth go with thee; he will not fail thee, nor forsake thee.",
        "topic": "Courage",
        "explanation": "Moses speaks this to an entire nation about to cross into unknown territory under new leadership. The command to not be afraid is not a denial of the danger — it is a redirection of attention to the companion. God going with you doesn't remove the risk; it changes the odds.",
        "reflection": "What 'Canaan' are you standing at the edge of, paralysed?",
        "application": "Take one step today that you've been postponing because you were waiting to feel ready.",
        "memory": "He goes with you. That changes the calculation.",
        "prayer": "Lord, I'm standing at an edge. Walk into it with me. Amen.",
    },
    {
        "reference": "Romans 15:13",
        "text": "Now the God of hope fill you with all joy and peace in believing, that ye may abound in hope, through the power of the Holy Ghost.",
        "topic": "Hope",
        "explanation": "Hope here is not optimism — it's a specific quality that God fills you with. Joy and peace come 'in believing' — they are companions to faith, not prerequisites for it. You don't have to feel hopeful to begin believing; you begin believing and hope follows.",
        "reflection": "In what area of your life has hope become the hardest thing to hold onto?",
        "application": "Tell one person today about something you're still hoping for, even if it feels fragile.",
        "memory": "Hope is something God fills you with — you cannot manufacture it alone.",
        "prayer": "God of hope, fill what in me has become empty. I can't produce this on my own. Amen.",
    },
    {
        "reference": "1 Thessalonians 5:18",
        "text": "In every thing give thanks: for this is the will of God in Christ Jesus concerning you.",
        "topic": "Gratitude",
        "explanation": "The verse does not say 'for everything' — it says 'in everything.' There is a significant difference. You don't have to be thankful that a hard thing happened; you can be thankful while it is happening. Gratitude is a posture, not always a feeling.",
        "reflection": "What is something currently difficult that you could find something to be grateful for in — not for, but in?",
        "application": "Before bed tonight, name one thing from today's difficulty you can acknowledge with gratitude.",
        "memory": "Gratitude is in the difficulty — not instead of it.",
        "prayer": "Lord, teach me to be grateful inside the hard seasons, not only after them. Amen.",
    },
    {
        "reference": "Micah 7:18",
        "text": "Who is a God like unto thee, that pardoneth iniquity, and passeth by the transgression of the remnant of his heritage? he retaineth not his anger for ever, because he delighteth in mercy.",
        "topic": "Forgiveness",
        "explanation": "The question 'who is a God like you?' is rhetorical — the answer is no one. What distinguishes God here is not power but mercy. He delights in forgiveness; it is not reluctant. The word 'delight' suggests that showing mercy is something God is drawn toward, not merely willing to do.",
        "reflection": "Do you experience God's forgiveness as reluctant or delighted? Where did that come from?",
        "application": "Receive forgiveness for something specific today — speak it out: 'This is forgiven.'",
        "memory": "God delights in mercy — it is not a concession.",
        "prayer": "Lord, I've been treating Your forgiveness as if You give it grudgingly. Thank You for showing me otherwise. Amen.",
    },
    {
        "reference": "Colossians 3:13",
        "text": "Forbearing one another, and forgiving one another, if any man have a quarrel against any: even as Christ forgave you, so also do ye.",
        "topic": "Forgiveness",
        "explanation": "The standard given is not 'forgive if you feel ready' but 'forgive as you have been forgiven.' This makes forgiveness less about the other person's deservingness and more about what you've already received. You forgive from a position of having been forgiven first.",
        "reflection": "Is there someone you are waiting to forgive until they 'deserve' it?",
        "application": "Take one step toward forgiveness today — even if it's just deciding to release the right to stay angry.",
        "memory": "You forgive from abundance, not from strength.",
        "prayer": "Lord, I'm holding something. Help me release it — not because they deserve it, but because You did it for me. Amen.",
    },
    {
        "reference": "John 3:16",
        "text": "For God so loved the world, that he gave his only begotten Son, that whosoever believeth in him should not perish, but have everlasting life.",
        "topic": "Love",
        "explanation": "The word 'so' carries the weight of this verse — it speaks to the manner and the measure of love, not just its existence. God loved in a way that cost everything. The offer is to 'whosoever' — there is no conditional that narrows it before the verb 'believeth.'",
        "reflection": "Do you experience yourself as genuinely included in 'whosoever' — or do you carry an asterisk?",
        "application": "Say this verse slowly, replacing 'the world' with your own name.",
        "memory": "The love that saves is the love that first saw you.",
        "prayer": "God, I've heard this verse so many times it's stopped landing. Let it land again today. Amen.",
    },
    {
        "reference": "2 Timothy 1:7",
        "text": "For God hath not given us the spirit of fear; but of power, and of love, and of a sound mind.",
        "topic": "Courage",
        "explanation": "Fear is identified here as something with a source — and the source is not God. Power, love, and a sound mind are the counter-gifts. A sound mind means one that is not fragmented by panic — the kind of clear thinking that fear destroys.",
        "reflection": "Where is fear currently doing the most damage to your clarity or your relationships?",
        "application": "Identify one fear-driven decision you've made recently. Ask: what would the 'sound mind' version of that decision look like?",
        "memory": "Fear is not your inheritance — power and clarity are.",
        "prayer": "Lord, fear has been louder than Your voice lately. I'm asking You to speak clearly today. Amen.",
    },
    {
        "reference": "Psalm 27:1",
        "text": "The Lord is my light and my salvation; whom shall I fear? The Lord is the strength of my life; of whom shall I be afraid?",
        "topic": "Courage",
        "explanation": "The questions are rhetorical, but they are worth sitting with literally: who, specifically, are you afraid of? What, specifically, do you fear will be taken from you? The Psalm doesn't deny fear — it challenges fear with a counter-claim about who God is.",
        "reflection": "What or who would you name as an honest answer to 'whom shall I fear' in your life right now?",
        "application": "Write the specific name of what you're afraid of. Next to it, write: 'The Lord is my light in this.'",
        "memory": "Name your fear. Then name your God. The order matters.",
        "prayer": "Lord, I'm naming what I'm afraid of rather than hiding it. Now I'm naming You as larger. Amen.",
    },
    {
        "reference": "Ephesians 4:32",
        "text": "And be ye kind one to another, tenderhearted, forgiving one another, even as God for Christ's sake hath forgiven you.",
        "topic": "Forgiveness",
        "explanation": "Tenderhearted — the original word means 'good-boweled,' which is the ancient way of saying moved deeply in your core. Kindness here is not surface politeness; it is a posture of being genuinely moved by someone else's situation. Forgiveness flows from this posture.",
        "reflection": "Who in your life have you stopped being tenderhearted toward?",
        "application": "Do one unexpectedly kind thing for someone today — especially someone it doesn't come naturally toward.",
        "memory": "Kindness before forgiveness makes forgiveness possible.",
        "prayer": "Lord, I've gone hard toward some people. Soften what has become rigid in me. Amen.",
    },
]


def get_offline_devotional() -> dict:
    """
    Return today's offline devotional deterministically by day of year.
    Cycles through the list so each day gets a different one.
    """
    day_idx = date.today().timetuple().tm_yday  # 1-366
    idx = (day_idx - 1) % len(OFFLINE_DEVOTIONALS)
    d = dict(OFFLINE_DEVOTIONALS[idx])
    d["_quota_error"] = True
    d["translation_id"] = "KJV"
    return d